version : "3"
services:
      mysql:
              image: mysql:5.7
              container_name: mysql
              privileged: true
              ports:
                      - 3307:3306
              environment:
                      MYSQL_ROOT_PASSWORD: root
              volumes:
                    - ./mysql5:/var/lib/mysql
      php:
              image: php:7.2-fpm
              container_name: php
              privileged: true
              ports:
                    - 9001:9000
              links:
                     - mysql

              volumes:
                     - ./nginx/apps:/usr/share/nginx/html
      nginx:
               image:  nginx
               container_name: nginx
               privileged: true
               links:
                       - php
               ports:
                       - 8088:8088
                       - 9099:9099
               volumes:
                       - ./nginx/vhost:/www/nginx/vhost
                       - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
                       - ./nginx/log:/www/nginx/log
                       - ./nginx/apps:/usr/share/nginx/html

      phpmyadmin:
              image: phpmyadmin/phpmyadmin
              container_name: phpmyadmin
              privileged: true
              links:
                      - mysql
              ports:
                      - 7001:80
              environment:
                      MYSQL_ROOT_PASSWORD: root
                      PMA_HOST: mysql

      redis:
              image: redis:4.0.14
              container_name: redis
              privileged: true
              ports:
                      - 6379:6379
      mongo:
              image: mongo
              restart: always
              ports:
                      - 27017:27017